// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WinFormsApp1.Models;

public partial class Order
{
    public int Id { get; set; }

    public int? ProductId { get; set; }

    public int Amount { get; set; }

    public DateOnly OrderDate { get; set; }

    public virtual double Sum { get; set; }

    [NotMapped]
    public virtual Product Product { get; set; }
}