// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WinFormsApp1.Models;

public partial class Order
{
    public int Id { get; set; }

    public int? ProductId { get; set; }

    public int Amount { get; set; }

    public DateOnly OrderDate { get; set; }

    public double Sum { get; set; }

    public virtual Product Product { get; set; }
}